/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadoraapp;


import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import utils.edu.fpoo.mundo.Calculadora;

/**
 *
 * @author Ayala
 */
public class FormularioCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form FormularioCalculadora
     */
    public FormularioCalculadora() {
        initComponents();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ejemplo de Calculadora con SWING");
        setSize(550, 380);
        setLocation(200, 200);
        setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfNumero1 = new javax.swing.JTextField();
        tfNumero2 = new javax.swing.JTextField();
        tfDividir = new javax.swing.JTextField();
        tnbSumar = new javax.swing.JToggleButton();
        btnRestar = new javax.swing.JToggleButton();
        btnMultiplicar = new javax.swing.JToggleButton();
        btnDividir = new javax.swing.JToggleButton();
        btnLimpiar = new javax.swing.JToggleButton();
        btnSalir = new javax.swing.JToggleButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        tfSuma = new javax.swing.JTextField();
        tfResta = new javax.swing.JTextField();
        tfMultiplica = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        jTextField2.setText("jTextField2");

        jTextField3.setText("jTextField3");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Calcualdora"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Número 2:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 81, -1, -1));

        jLabel2.setText("Número 1:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 39, -1, -1));

        jLabel3.setText("Resultado");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        tfNumero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNumero1ActionPerformed(evt);
            }
        });
        jPanel1.add(tfNumero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 36, 120, -1));

        tfNumero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNumero2ActionPerformed(evt);
            }
        });
        jPanel1.add(tfNumero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 78, 120, -1));
        jPanel1.add(tfDividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 80, -1));

        tnbSumar.setText("Sumar");
        tnbSumar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tnbSumar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tnbSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnbSumarActionPerformed(evt);
            }
        });
        jPanel1.add(tnbSumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 172, 70, -1));

        btnRestar.setText("Restar");
        btnRestar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRestar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRestar, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 207, 70, -1));

        btnMultiplicar.setText("Multiplicar");
        btnMultiplicar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMultiplicar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicarActionPerformed(evt);
            }
        });
        jPanel1.add(btnMultiplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 252, 70, -1));

        btnDividir.setText("Dividir");
        btnDividir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDividir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDividirActionPerformed(evt);
            }
        });
        jPanel1.add(btnDividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 293, 70, -1));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 70, -1));

        btnSalir.setText("Salir");
        btnSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 70, -1));
        jPanel1.add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        jPanel1.add(filler2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        jPanel1.add(tfSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 80, -1));
        jPanel1.add(tfResta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 80, -1));
        jPanel1.add(tfMultiplica, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 80, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadoraapp/LogoAzul.jpeg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDividirActionPerformed
      String Dividir;
        realizarOperacion(Dividir="Dividir");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDividirActionPerformed

    private void tfNumero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNumero2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNumero2ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed

        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void tnbSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnbSumarActionPerformed
        String suma;
        realizarOperacion(suma="Sumar");
    }//GEN-LAST:event_tnbSumarActionPerformed

    private void btnRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestarActionPerformed
        String Resta;
        realizarOperacion(Resta= "Restar");
            // Validar que los campos no estén vacío
    }//GEN-LAST:event_btnRestarActionPerformed

    private void btnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicarActionPerformed
        String Multiplicar;
        realizarOperacion(Multiplicar="Multiplicar");
    }//GEN-LAST:event_btnMultiplicarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed

        tfMultiplica.setText("");
        tfSuma.setText("");
        tfResta.setText("");
        tfDividir.setText("");
       tfNumero1.setText("");
       tfNumero2.setText("");
        
       
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void tfNumero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNumero1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNumero1ActionPerformed


    
    
    
    private void realizarOperacion(String operacion) {
    Calculadora calculadora = new Calculadora();
    
try {
    // Validar campos vacíos
    if (tfNumero1.getText().isEmpty() || tfNumero2.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Los campos no pueden estar vacíos","SIN DATOS",2);
        return;
    }
    
    // Validar que ambos campos contengan solo números (enteros o decimales)
    String texto1 = tfNumero1.getText().trim();
    String texto2 = tfNumero2.getText().trim();
    
    // Expresión regular para validar números (enteros o decimales)
    String patronNumero = "^[0-9]+(\\.[0-9]+)?$";
    
    if (!texto1.matches(patronNumero)) {
        JOptionPane.showMessageDialog(this, 
            "Tipo de dato #1 no valido (solo se permiten numero", 
            "ERROR DE TIPO DE DATO", 2);
        return;
    }
    
    if (!texto2.matches(patronNumero)) {
        JOptionPane.showMessageDialog(this, 
           "Tipo de dato #2 no valido (solo se permiten numero", 
            "ERROR DE TIPO DE DATO", 2);
        return;
    }
    
    // Convertir a double (ahora sabemos que son válidos)
    double operando1 = Double.parseDouble(texto1);
    double operando2 = Double.parseDouble(texto2);
    
    // Validar división entre cero
    if (operacion.equals("Dividir") && operando2 == 0) {
        JOptionPane.showMessageDialog(this, 
            "LA DIVION POR CERO NO ESTA DEFINIDA", 
            "ERROR DE DIVISIÓN", 2);
        return;
    }
    
    calculadora.setM_operando1(operando1);
    calculadora.setM_operando2(operando2);
    
    double resultado = 0;
    switch(operacion) {
        case "Sumar":
            resultado = calculadora.Sumar();
            tfSuma.setText(String.valueOf(resultado));
            break;
        case "Restar":
            resultado = calculadora.Restar();
            tfResta.setText(String.valueOf(resultado));
            break;
        case "Multiplicar":
            resultado = calculadora.Multiplicar();
            tfMultiplica.setText(String.valueOf(resultado));
            break;
        case "Dividir":
            resultado = calculadora.Dividir();
            tfDividir.setText(String.valueOf(resultado));
            break;
    }
    
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, 
        "Error inesperado en el formato de números", 
        "ERROR", 2);
}
}
    
    
    
    
    







    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnDividir;
    private javax.swing.JToggleButton btnLimpiar;
    private javax.swing.JToggleButton btnMultiplicar;
    private javax.swing.JToggleButton btnRestar;
    private javax.swing.JToggleButton btnSalir;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField tfDividir;
    private javax.swing.JTextField tfMultiplica;
    private javax.swing.JTextField tfNumero1;
    private javax.swing.JTextField tfNumero2;
    private javax.swing.JTextField tfResta;
    private javax.swing.JTextField tfSuma;
    private javax.swing.JToggleButton tnbSumar;
    // End of variables declaration//GEN-END:variables
}
